runtime: python27
api_version: 1
threadsafe: true
service: webapp

libraries:
- name: ssl
  version: latest

handlers:
- url: /.*
  script: app.app

skip_files:
  - vendor/docker/
  - vendor/kubernetes/

env_variables:
  COWBULL_PROTOCOL: "http"
  COWBULL_SERVER: "cowbull-test-project.appspot.com"
  COWBULL_VERSION: "v1"
  COWBULL_PORT: 80
  LOGGING_LEVEL: 10
