runtime: python27
api_version: 1
threadsafe: true
service: webapp

handlers:
- url: /.*
  script: app.app

skip_files:
  - vendor/docker/
  - vendor/kubernetes/

env_variables:
  COWBULL_SERVER: "cowbull-test-project.appspot.com"
  COWBULL_PORT: 80
  LOGGING_LEVEL: 10
