runtime: python37
service: webapp

handlers:
- url: /.*
  script: auto

env_variables:
  COWBULL_PROTOCOL: "https"
  COWBULL_SERVER: "djsanders-dev-spaces.ue.r.appspot.com"
  COWBULL_VERSION: "v1"
  COWBULL_PORT: 443
  LOGGING_LEVEL: 10
