steps:
- name: 'python:3.6.10-alpine3.11'
  args: [
    '/bin/sh',
    './cloudbuild_test.sh'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/personal-dev-272223/cowbull_webapp:${_BUILD_NUMBER}', 
    '.' 
  ]
substitutions:
  _BUILD_NUMBER: "20.04-22"
images:
- 'gcr.io/personal-dev-272223/cowbull_webapp:${_BUILD_NUMBER}'
artifacts:
  objects:
    location: 'gs://dasander-artifacts/cowbull_webapp'
    paths: ['coverage.xml']