steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/personal-dev-272223/cowbull_webapp:${_BUILD_NUMBER}', 
    '.' 
  ]
substitutions:
  _BUILD_NUMBER: "20.04-14"
images:
- 'gcr.io/personal-dev-272223/cowbull_webapp:${_BUILD_NUMBER}'
