version: '2'

services:
  redis:
    image: 'redis:latest'
    networks:
      - cowbull_network
    restart: always
  cowbull_svc:
    image: 'dsanderscan/cowbull'
    depends_on:
      - redis
    environment:
      - LOGGING_LEVEL=10
      - 'PERSISTER={"engine_name": "redis", "parameters": {"host": "redis", "port": 6379, "db": 0}}'
    networks:
      - cowbull_network
    restart: always
  cowbull_webapp:
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    depends_on:
      - cowbull_svc
    ports:
      - 9080:8080
    environment:
      - COWBULL_SERVER=cowbull_svc
      - COWBULL_PORT=8080
      - COWBULL_VERSION=v1
    networks:
      - cowbull_network
networks:
  cowbull_network:
