version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: dsanderscan/cowbull

    working_directory: ~/python_cowbull_webapp

    environment:
      - PERSISTER: '{"engine_name": "redis", "parameters": {"host": "localhost", "port": 6379, "db": 0}}'

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip2 install -r requirements.txt

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            set -o pipefail
            python -m unittest -v tests 2> >(tee -a /tmp/unittest-report.log >&2)

      - setup_remote_docker

      - run:
          name: build and test docker image
          command: |
            docker login --username=$doclog --password=$docpass
            docker build -f vendor/docker/Dockerfile -t dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM .
            set -o pipefail
            docker run --name cowbull -d dsanderscan/cowbull
            docker run --name test2 --link cowbull \
              -v /tmp:/tmp \
              -e COWBULL_SERVER='http://cowbull' \
              -e COWBULL_PORT=5000 \
              -d dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM \
              bash -c 'python -m unittest -v tests 2> >(tee -a /tmp/dockertest-report.log >&2)'
            echo "Test results status: $?"

      - run:
          name: push docker image
          command: |
            docker tag dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM dsanderscan/$IMAGE_NAME:latest
            docker push dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM
            docker push dsanderscan/$IMAGE_NAME:latest
      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: /tmp/unittest-report.log
          destination: unittest-report

      - store_artifacts:
          path: /tmp/dockertest-report.log
          destination: dockertest-report