version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/python_cowbull_webapp

    environment:
      - COWBULL_SERVER='cowbull'
      - COWBULL_PORT=8080

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip2 install -r requirements.txt

      - setup_remote_docker

      - run:
          name: build and test docker image
          command: |
            docker login --username=$doclog --password=$docpass
            docker build -f vendor/docker/Dockerfile -t dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM .
            set -o pipefail
            docker run --name redis \
              -d dsanderscan/python_cowbull_redis:$cowbull_redis_version \
              redis-server
            docker run --name cowbull \
              --link redis \
              -e "PERSISTER"='{"engine_name": "redis", "parameters": {"host": "redis", "port": 6379, "master_port": 26379, "db": 0}}' \
              -e LOGGING_LEVEL=10 \
              -d dsanderscan/cowbull:$cowbull_test_version
            docker run --name test2 \
              --link cowbull \
              -v /tmp:/tmp \
              -e COWBULL_SERVER='cowbull' \
              -e COWBULL_PORT=8080 \
              -e LOGGING_LEVEL=10 \
              -e COWBULL_ENVIRONMENT="CI/CD" \
              -e BUILD_NUMBER="TEST-"$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM \
              -p 8080:8080 \
              -d dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM \
              python -m unittest -v tests 2> >(tee -a /tmp/unittest-report.log >&2); sleep 10000
            docker cp test2:/tmp/unittest-report.log /tmp/unittest-report.log
            docker stop test2
            echo "Test results status: $?"

      - run:
          name: push docker image
          command: |
            docker tag dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM dsanderscan/$IMAGE_NAME:latest
            docker push dsanderscan/$IMAGE_NAME:$MAJOR_VERSION"."$MINOR_VERSION"."$CIRCLE_BUILD_NUM
            docker push dsanderscan/$IMAGE_NAME:latest

      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: /tmp/unittest-report.log
          destination: unittest-report
